name: commandline_or_gui_windows
description: Allows your app to run as either commandline or gui. Windows only.
version: 2.2.0
repository: https://github.com/Honeyman-Applications/commandline_or_gui_windows

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  args: ^2.5.0
  universal_platform: ^1.0.0+1
  package_config: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

