name: commandline_or_gui_windows
description: Allows your app to run as either commandline or gui. Windows only.
version: 2.1.2
repository: https://github.com/Honeyman-Applications/commandline_or_gui_windows

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  args: ^2.3.1
  package_config: ^2.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      windows:
        pluginClass: CommandlineOrGuiWindowsPlugin

